# Generated by Django 4.2.5 on 2023-10-31 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bodega',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='categoria',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='objeto',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='vehiculo',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='bodega',
            name='capacidad',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='capacidad',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='volumen_carga',
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='capacidad_max',
            field=models.IntegerField(default=60, verbose_name='Capacidad maxima del vehiculo'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='capacidad_min',
            field=models.IntegerField(default=1, verbose_name='Capacidad minima del vehiculo'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='volumen_carga_max',
            field=models.IntegerField(default=120, verbose_name='Volumen maximo de carga (m³)'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='volumen_carga_min',
            field=models.IntegerField(default=2, verbose_name='Volumen minimo de carga (m³)'),
        ),
        migrations.AlterField(
            model_name='bodega',
            name='area',
            field=models.FloatField(blank=True, null=True, verbose_name='Area (m²)'),
        ),
        migrations.AlterField(
            model_name='bodega',
            name='volumen',
            field=models.FloatField(blank=True, null=True, verbose_name='Volumen (m³)'),
        ),
        migrations.AlterField(
            model_name='calculo',
            name='objetos',
            field=models.ManyToManyField(to='api.objeto', verbose_name='Objetos seleccionados'),
        ),
    ]
