# Generated by Django 4.2.5 on 2023-11-21 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_name_bodega_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objeto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.categoria', verbose_name='Categoria'),
        ),
    ]
